### ISSUE TITLE
Grouping of notifications 

### ISSUE THREAD

**Issue by SimonHeese** [jsecretan/maven-public#11]
Is:

- Notifications are listed by author
- Autor names are most prominent items in UI

Potential improvement:

- group notifications by thread/topic 
- group updates since last own post or page view 

Rationale 
- discussions on the platform are rather represented in users brains as topic threads and less by users
- currently there are only a few active users, so it's xyz commented here and there which adds even more noise

**Comment by jsecretan** [comment]
We have now ported the grouping from mobile over to the web
