### ISSUE TITLE
Touching left margin will cause refresh

### ISSUE THREAD

**Issue by murphyd** [jsecretan/maven-public#12]
When reading a conversation, if you tap on the left hand side of the screen, usually in the comments, the screen will refresh. 

Generally, this isn’t a problem, but if you’ve added text into the text input box and have not sent it yet, the refresh will erase the text from the input box and it must be re-entered again.

I’ve noticed this on iOS / iPadOS version 1.0.6 (2).

Video here: https://drive.google.com/file/d/1P9qJ_SOHPFizBim6mFU7mDI3ckkEPfrR/view?usp=sharing

**Comment by jsecretan** [comment]
Ok thanks for this one, I knew something was wrong, but I was having trouble figuring it out

**Comment by jsecretan** [comment]
This is now fixed in the new versions
