### ISSUE TITLE
[old + beta] Navigating from an old thread to a new one doesn't refresh comments

### ISSUE THREAD

**Issue by flockonus** [jsecretan/maven-public#15]
Say i'm at https://beta.heymaven.com/discover/46935 

To which i see related:

![image](https://github.com/jsecretan/maven-public/assets/165553/4c33e003-d04d-4999-a686-2e3ee95c51f7)

Navigate to https://beta.heymaven.com/discover/35478 and back, and to another one (or this same one again) - comments look empty or re-rendered from a previous thread i've seen

**Comment by jsecretan** [comment]
I think we have fixed this on beta, maybe you could take a look when you get a chance?
