### ISSUE TITLE
[web beta] What does "Reverie" refer to?

### ISSUE THREAD

**Issue by PhilMunk** [jsecretan/maven-public#16]
This needs either a tooltip for explanation or renaming to familiar Maven nomenclature. 

![image](https://github.com/jsecretan/maven-public/assets/163876745/ee845e2c-1b6d-469b-861a-30bf34a9589e)

**Comment by jsecretan** [comment]
Thanks, I've fixed this language.  If you curious about the origin, "Reverie" is what we used to call all posts, because originally it was a very different format than a social media post, and more of a statement to help us match you.

**Comment by PhilMunk** [comment]
Same issue still exists in "Notifications" ;)
