### ISSUE TITLE
Post 49453 does not load

### ISSUE THREAD

**Issue by Crul** [jsecretan/maven-public#25]
I'm getting errors when trying to access https://app.heymaven.com/discover/49453

If I'm logged in, the request to https://api.heymaven.com/api/v1/reveries/49453 works (200 OK) and I see this Javascript error:

`e.data.data is undefined   index.tsx:295:25`

I I'm not logged in, the request to https://api.heymaven.com/api/v1/reveries/49453 fails (500 Internal Server Error) and it returns this error:

`{"status":500,"error":"Internal Server Error"}`

**Comment by daia99** [comment]
I think I see this related error, too (some newer replies deeper in the post not loading) - for example, in posts 27213 and 48562.

Scrolling down to try to load new replies (on both iOS and web) seems to hang on loading.

I haven't seen any other issue posted on this, maybe it's more recent?

**Comment by Crul** [comment]
For tracking purposes.

[Jimmy Secretan on Maven](https://app.heymaven.com/discover/49990)
> Hi Crul, do me a favor, can you go to your "Drafts" (either on the left side menu on web, or at the top of your profile page on mobile) and see if it is there. It looks like that post is currently unpublished. It may have errored out during publish and silently returned (which we will of course look into).


[Crul's on Maven](https://app.heymaven.com/discover/50016)
> Indeed it was there. I tried publishing it (I didn't record the HTTP requests :/) but it still throws the same error reported on github. And now it's not on Drafts either.
>
>> It looks like that post is currently unpublished. It may have errored out during publish and silently returned (which we will of course look into).
>
> Note that the thread has some comments from multiple users. So (if I understand correctly) it must have been published at some point.
>
> Thanks!

**Comment by Crul** [comment]
I just remembered that I tried uploading an image for the post and it didn't work. Wanted to say just in case is related to that.

**Comment by Crul** [comment]
Solved!
