### ISSUE TITLE
Unable to login/create user on mobile app for users in countries with less than 9 digits in phone numbers

### ISSUE THREAD

**Issue by KvaGram** [jsecretan/maven-public#31]
Description:
On the mobile app, the phone number entry screen's next button (red right-arrow) is disabled until at least 9 digits are entered.
Author of this issue lives in Norway, and has a phone number with eight (8) digits, and is thus unable to use the Maven phone app.

Recreate:
Open app, if logged in, log out. Choose new user with phone number, or select log in.
Pick a country from the list with less than 9 digits in their phone numbers. ([A list like this may be of help](https://worldpopulationreview.com/country-rankings/phone-number-length-by-country))
Write/tap in a valid phone number for that country.

Observed behavior:
Dark red right-arrow remains dark. Button remains locked.

Expected behavior:
Dark red right-arrow turns light red. Button is unlocked.

Proposed solution:
Reprogram the UI to take the country-code into account when deciding whatever the next-button is enabled or not.

**Comment by jsecretan** [comment]
Thanks, we figured out the issue here and we'll fix it in the next release.  In the mean time, I've confirmed that it should be ok in the web version

**Comment by jsecretan** [comment]
This should be fixed in the latest mobile versions now
