### ISSUE TITLE
Cannot open a thread in a new tab in the browser.

### ISSUE THREAD

**Issue by volotat** [jsecretan/maven-public#34]
When I press on the thread name with the right mouse button in the browser there is no "Open Link in New Tab" option that is usually available when pressing on the link. That is quite uncomfortable as I cannot move to the thread without closing the discovery page. Pressing ctrl + left mouse button does not work either and the thread simply opens in the same page as I was before.

**Comment by jsecretan** [comment]
Thanks, this fix is in beta now and I'll put it out in the next release.
