### ISSUE TITLE
Changing Serendipity settings should trigger a reload.

### ISSUE THREAD

**Issue by PhilMunk** [jsecretan/maven-public#36]
Currently when changing Serendipity settings it does not reload the page to reveal the changed Discover feed. So you change the settings but the feed stays the same, until you reload the page manually. I have seen this causing some confusion.

**Comment by PhilMunk** [comment]
Seems like this has been implemented by now. Feel free to close, @jsecretan

**Comment by jsecretan** [comment]
Thanks @PhilMunk
