### ISSUE TITLE
A lot of notifications are missing

### ISSUE THREAD

**Issue by PhilMunk** [jsecretan/maven-public#37]
I see a lot of activity in threads where I have commented before, without receiving notifications.
This is either due to a bug or the triggers for receiving notifications have changed without me understanding the logic.

**Comment by PhilMunk** [comment]
Note: all my Muted Lists are empty

**Comment by PhilMunk** [comment]
I am not seeing these symptoms at the moment anymore.
But I wont close this issue myself yet.
I will add another comment if I see it happening again.

**Comment by PhilMunk** [comment]
Found a new example ... this is still a problem.

**Comment by jsecretan** [comment]
@PhilMunk are you still seeing this?  We had deployed something to limit the number of notifications per day per thread.  But I have made a deploy now restricting this to only limiting the actual push and not the in app one.

**Comment by PhilMunk** [comment]
@jsecretan 
Ah, that makes sense. Matches up with what I observed.
I will keep my eyes open and report if I see a new examples.
But given your latest fix, this should be fine now. Limiting pushes makes sense.

**Comment by jsecretan** [comment]
Closing this as it seems ok now
