### ISSUE TITLE
[EXTREMELY URGENT] Make Maven opt-in or, at least, provide a method to opt out

### ISSUE THREAD

**Issue by StarkRG** [jsecretan/maven-public#46]
You are currently stealing content from other people and using it for your own purposes without permission. This needs to stop.

**Comment by jsecretan** [comment]
We are no longer ingesting ActivityPub content.

**Comment by SuperContraptionGuy** [comment]
There must be a better way this could have been done. This platform really does need to interoperate with ActivityPub and the fediverse, in addition to as many other social media platforms as it can. The real power here I think is, assuming the topical distance algorithm is any good, connecting content and people from across the web. I think it'd be pretty sad if it didn't also contribute to ActivityPub.
