### ISSUE TITLE
An overview for "Muted Users" [now available in web beta]

### ISSUE THREAD

**Issue by PhilMunk** [jsecretan/maven-public#6]
I would like to be able to see all Users that I have Muted without looking at everyone's Profile individually.

A "Muted Users" tab on my Profile page (only visible to myself) would be perfect.

**Comment by jsecretan** [comment]
This is now available in TestFlight and we'll get it out for the next release.

**Comment by PhilMunk** [comment]
Works in the web-beta branch.

I am not sure if I am supposed to close this issue myself now, leave it open until rollout into main-branch and mobile apps, or leave the closing up to @jsecretan  in general.

**Comment by jsecretan** [comment]
Thanks @PhilMunk I'll close this out once I've QA'ed it for both the mobile and web

**Comment by jsecretan** [comment]
Closing this out now that we are released, thanks for this great suggestion @PhilMunk!
